# Why we are running with network_mode: host
# Wow this has been awful. We run three things in docker: mysql, keycloak, and the backend server.
# The backend-server needs to talk to the other two.
#
# In order to talk to keycloak, it needs to go through localhost so that it can communicate with
# keycloak using the same url as the frontend so that tokens can be properly validated.
# If the domains are different, keycloak invalidates the token. There may be a way to change
# this but I didn't find it.
#
# In order for the backend server to talk to the mysql server, they need to be on the same network.
# I tried splitting it out where the mysql runs on a custom network and the backend runs on both
# the custom network AND with localhost. Nothing I tried worked and googling didn't help. They
# only ever mentioned one thing or using host.docker.internal which would cause the domains to
# be different.
#
# So instead we are running with both the mysql server and the backend server in host netowrk mode.
# There may be a better way to do this but if it works, then it works.

version: "3.8"
include:
  - db-docker-compose.yml
services:
  spiffworkflow-backend: &spiffworkflow-backend
    container_name: spiffworkflow-backend-api
    profiles:
      - run
    depends_on:
      spiffdb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
      - FLASK_SESSION_SECRET_KEY=${FLASK_SESSION_SECRET_KEY:-e7711a3ba96c46c68e084a86952de16f}
      - SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR=/app/process_models
      - SPIFFWORKFLOW_BACKEND_ENV=${SPIFFWORKFLOW_BACKEND_ENV:-local_development}
      - SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA=${SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA:-false}
      - SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME=${SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME:-acceptance_tests.yml}
        # the background scheduler picks up process instances that we set in a certain state and then runs them like running not_started instances
        # that are required for the process instance filter test. So for now do not run it. we may want to find another way around in the future
      - SPIFFWORKFLOW_BACKEND_RUN_BACKGROUND_SCHEDULER_IN_CREATE_APP=false
      - SPIFFWORKFLOW_BACKEND_UPGRADE_DB=true
    ports:
      - "8000:8000"
    volumes:
      - ${SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR:-../../sample-process-models}:/app/process_models
      - ./log:/app/log
    networks:
      - forms-flow-spiff-network
    command: /app/bin/boot_server_in_docker
    healthcheck:
      test: curl localhost:8000/v1.0/status --fail
      interval: 10s
      timeout: 5s
      retries: 20

  spiffworkflow-backend-local-debug:
    <<: *spiffworkflow-backend
    container_name: spiffworkflow-backend-local-debug
    profiles:
      - debug
    volumes:
      - ${SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR:-../../sample-process-models}:/app/process_models
      - ./:/app
    command: /app/bin/boot_in_docker_debug_mode

    # the docs say we can disable healthchecks with disable: true
    # but it returns a bad exit code so setup one that doesn't matter
    # since there is nothing to healthcheck in this case
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
    healthcheck:
      test: cat /etc/hosts
      interval: 10s
      timeout: 5s
      retries: 20
  spiffworkflow-backend-celery:
    depends_on:
      spiffdb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
      - FLASK_SESSION_SECRET_KEY=${FLASK_SESSION_SECRET_KEY:-e7711a3ba96c46c68e084a86952de16f}
      - SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR=/app/process_models
      - SPIFFWORKFLOW_BACKEND_ENV=${SPIFFWORKFLOW_BACKEND_ENV:-local_development}
      - SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA=${SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA:-false}
      - SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME=${SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME:-acceptance_tests.yml}
        # the background scheduler picks up process instances that we set in a certain state and then runs them like running not_started instances
        # that are required for the process instance filter test. So for now do not run it. we may want to find another way around in the future
      - SPIFFWORKFLOW_BACKEND_RUN_BACKGROUND_SCHEDULER_IN_CREATE_APP=false
      - SPIFFWORKFLOW_BACKEND_UPGRADE_DB=true
    volumes:
      - ${SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR:-../../sample-process-models}:/app/process_models
      - ./log:/app/log
    networks:
      - forms-flow-spiff-network
    healthcheck:
      test: cat /etc/hosts
      interval: 10s
      timeout: 5s
      retries: 20
    command: /app/bin/start_celery_worker

volumes:
  spiffworkflow_backend:
    driver: local
networks:
  forms-flow-spiff-network:
    driver: 'bridge'