# version: "3.8"
include:
  - ./spiffworkflow-backend/docker-compose.yml
services:
  spiffworkflow-connector:
    container_name: spiffworkflow-connector
    image: ghcr.io/sartography/connector-proxy-demo:latest
    environment:
      FLASK_ENV: "${FLASK_ENV:-development}"
      FLASK_DEBUG: "0"
      FLASK_SESSION_SECRET_KEY: "${FLASK_SESSION_SECRET_KEY:-super_secret_key}"
      CONNECTOR_PROXY_PORT: "${SPIFF_CONNECTOR_PORT:-8004}"
    ports:
      - "${SPIFF_CONNECTOR_PORT:-8004}:${SPIFF_CONNECTOR_PORT:-8004}/tcp"
    healthcheck:
      test: "curl localhost:${SPIFF_CONNECTOR_PORT:-8004}/liveness --fail"
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  spiffworkflow_backend_db:
    driver: local
