"""added tenant key to remaining models

Revision ID: 345ccc676bbf
Revises: e313d36507f8
Create Date: 2025-04-17 13:07:22.898618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345ccc676bbf'
down_revision = 'e313d36507f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bpmn_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('bpmn_process_definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('message_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    with op.batch_alter_table('task_definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_definition', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('message_instance', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('bpmn_process_definition', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    with op.batch_alter_table('bpmn_process', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    # ### end Alembic commands ###
