"""added primary_process_id and primary_file_name

Revision ID: 8b50aa34be91
Revises: f31dfbe97509
Create Date: 2025-02-19 16:01:05.074696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b50aa34be91'
down_revision = 'f31dfbe97509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_model_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_file_name', sa.String(), nullable=True, allow_blank=True, allow_none=True))
        batch_op.add_column(sa.Column('primary_process_id', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_model_info', schema=None) as batch_op:
        batch_op.drop_column('primary_process_id')
        batch_op.drop_column('primary_file_name')

    # ### end Alembic commands ###
