"""added tenant key to process model

Revision ID: e313d36507f8
Revises: 8b50aa34be91
Create Date: 2025-04-15 23:17:56.518226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e313d36507f8'
down_revision = '8b50aa34be91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_model_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_key', sa.String(), nullable=True, allow_blank=True, allow_none=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_model_info', schema=None) as batch_op:
        batch_op.drop_column('tenant_key')

    # ### end Alembic commands ###
